// Generated by CoffeeScript 1.3.3
(function() {

  window.config = {
    host: "http://localhost:8888/genk/multitouch-erfgoed-genk/",
    screen_width: 1920,
    screen_height: 1080,
    block: {
      width: 214,
      height: 214
    },
    grid_size: {
      x: 14,
      y: 8
    },
    grid_free: {
      big: 2
    },
    region_size: {
      x: 6,
      y: 3
    },
    region_positions: {
      TOP_LEFT: {
        x: 0,
        y: 0
      },
      TOP: {
        x: 4,
        y: 0
      },
      TOP_RIGHT: {
        x: 10,
        y: 0
      },
      BOTTOM_LEFT: {
        x: 0,
        y: 5
      },
      BOTTOM: {
        x: 4,
        y: 5
      },
      BOTTOM_RIGHT: {
        x: 10,
        y: 5
      }
    }
  };

}).call(this);
