// Generated by CoffeeScript 1.3.3
(function() {
  var Content, ContentCollection,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Content = (function(_super) {

    __extends(Content, _super);

    function Content() {
      return Content.__super__.constructor.apply(this, arguments);
    }

    Content.prototype.defaults = {
      title: "Title",
      date: Date.now(),
      description: "Lorem ipsum dolor sit amet...",
      fiche: {
        title: "Titel",
        object: "Object",
        collection: "Collectie",
        material: "Materiaal"
      },
      location: {
        longitude: 50.0,
        lattitude: 4.5,
        zoom: 14
      }
    };

    Content.prototype.initialize = function() {
      return console.log("Content.initialize", this.get('title'), this.niceDate());
    };

    Content.prototype.niceDate = function() {
      var months;
      months = ["januari", "februari", "maart", "april", "mei", "juni", "juli", "augustus", "september", "oktober", "november", "december"];
      return this.get('date').getDate() + " " + months[this.get('date').getMonth()] + " " + this.get('date').getFullYear();
    };

    return Content;

  })(Backbone.Model);

  ContentCollection = (function(_super) {

    __extends(ContentCollection, _super);

    function ContentCollection() {
      return ContentCollection.__super__.constructor.apply(this, arguments);
    }

    ContentCollection.prototype.model = Content;

    ContentCollection.prototype.url = config.host + "api/content";

    ContentCollection.prototype.initialize = function() {
      return this.fetch();
    };

    return ContentCollection;

  })(Backbone.Collection);

  window.Content = Content;

  window.ContentCollection = ContentCollection;

}).call(this);
