// Generated by CoffeeScript 1.3.3
(function() {
  var Folder, FolderView,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Folder = (function(_super) {

    __extends(Folder, _super);

    function Folder() {
      return Folder.__super__.constructor.apply(this, arguments);
    }

    Folder.prototype.initialize = function() {
      return console.log("Folder.initialize");
    };

    return Folder;

  })(Backbone.Model);

  FolderView = (function(_super) {

    __extends(FolderView, _super);

    function FolderView() {
      return FolderView.__super__.constructor.apply(this, arguments);
    }

    FolderView.prototype.className = "folder";

    FolderView.prototype.initialize = function() {
      return console.log("FolderView.initialize");
    };

    FolderView.prototype.events = {
      "click": "click"
    };

    FolderView.prototype.click = function() {
      return console.log("FolderView.click");
    };

    FolderView.prototype.render = function() {
      var date, title;
      title = this.model.get('content').get('title');
      date = this.model.get('content').niceDate();
      this.$el.html("<h2>" + title + "</h2>\n<div class=\"date\">" + date + "</div>");
      return this;
    };

    return FolderView;

  })(Backbone.View);

  window.Folder = Folder;

  window.FolderView = FolderView;

}).call(this);
