// Generated by CoffeeScript 1.3.3
(function() {
  var Grid, GridView,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Grid = (function(_super) {

    __extends(Grid, _super);

    function Grid() {
      return Grid.__super__.constructor.apply(this, arguments);
    }

    Grid.prototype.defaults = {
      blocks: null,
      regions: null,
      data: null
    };

    Grid.prototype.initialize = function() {
      this.get("blocks").on("contentReset", this.contentReset, this);
      this.get("regions").on("change:active", this.regionsChange, this);
      return this.data = new Array();
    };

    Grid.prototype.contentReset = function() {
      return this.fillWithBlocks();
    };

    Grid.prototype.fillWithBlocks = function() {
      var i, _i, _ref, _results;
      _results = [];
      for (i = _i = 0, _ref = this.get("blocks").length; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        _results.push(this);
      }
      return _results;
    };

    Grid.prototype.regionsChange = function() {};

    Grid.prototype.val = function(x, y) {
      var data;
      data = this.get("data");
      return data[y * config.grid_size.x + x];
    };

    Grid.prototype.setVal = function(x, y, value) {
      var data;
      data = this.get("data");
      data[y * config.grid_size.x + x] = value;
      this.set({
        "data": data
      });
      return this.trigger("change:data");
    };

    Grid.prototype.setRegion = function(x, y) {
      var i, j, _i, _j, _ref, _ref1;
      x = Math.max(0, Math.min(x, config.grid_size.x - config.region_size.x));
      y = Math.max(0, Math.min(y, config.grid_size.y - config.region_size.y));
      for (i = _i = x, _ref = x + config.region_size.x - 1; x <= _ref ? _i <= _ref : _i >= _ref; i = x <= _ref ? ++_i : --_i) {
        for (j = _j = y, _ref1 = y + config.region_size.y - 1; y <= _ref1 ? _j <= _ref1 : _j >= _ref1; j = y <= _ref1 ? ++_j : --_j) {
          this.setVal(i, j, "r");
        }
      }
      return this.setVal(x, y, "R");
    };

    return Grid;

  })(Backbone.Model);

  GridView = (function(_super) {

    __extends(GridView, _super);

    function GridView() {
      return GridView.__super__.constructor.apply(this, arguments);
    }

    GridView.prototype.className = "grid";

    GridView.prototype.initialize = function() {
      _.bindAll(this);
      return this.model.on("change:data", this.render, this);
    };

    GridView.prototype.render = function() {
      var cell, row, table, x, y, _i, _j, _ref, _ref1;
      table = $("<table></table>");
      for (y = _i = 0, _ref = config.grid_size.y - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; y = 0 <= _ref ? ++_i : --_i) {
        row = $("<tr></tr>");
        table.append(row);
        for (x = _j = 0, _ref1 = config.grid_size.x - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; x = 0 <= _ref1 ? ++_j : --_j) {
          cell = $("<td class='col-" + x + " row-" + y + "' id='cell-" + x + "-" + y + "'></td>");
          cell.html(this.model.val(x, y));
          row.append(cell);
        }
      }
      this.$el.html(table);
      return this;
    };

    return GridView;

  })(Backbone.View);

  window.Grid = Grid;

  window.GridView = GridView;

}).call(this);
