// Generated by CoffeeScript 1.3.3
(function() {
  var App;

  App = (function() {
    return $(function($) {
      var wielerlegende;
      wielerlegende = new Content({
        title: "Wielerlegende schittert in Winterslag",
        date: new Date("1970-9-25")
      });
      new BlockView({
        model: new Block({
          content: wielerlegende
        })
      }).render().$el.appendTo($("#blocks"));
      return new FolderView({
        model: new Folder({
          content: wielerlegende
        })
      }).render().$el.appendTo($("#folders"));
    });
  })();

}).call(this);
