// Generated by CoffeeScript 1.3.3
(function() {
  var App;

  App = (function() {
    var init;
    init = function() {
      var index, reg1, reg2, that, _i, _len, _ref, _results;
      reg1 = 1;
      reg2 = 2;
      that = this;
      console.log("this", this);
      _ref = [0, 1, 2, 3, 4];
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        index = _ref[_i];
        console.log("index", index);
        _results.push((function() {
          var that_index;
          that_index = index;
          return setTimeout(function() {
            console.log("this", this, "that", that);
            console.log("reg1", reg1);
            return console.log("index", that_index);
          }, index * 1000);
        })());
      }
      return _results;
    };
    return {
      "init": init
    };
  })();

  App.init();

}).call(this);
